from domain.usecases.add_account import AddAccount, AddAccountModel
from domain.usecases.authentication import Authentication, AuthenticationModel, AuthenticationParams
from domain.usecases.load_account_by_token import LoadAccountByToken
from domain.usecases.add_survey import AddSurvey, AddSurveyAnswerParams, AddSurveyParams
from domain.usecases.load_surveys import LoadSurveys
from domain.usecases.check_survey_by_id import CheckSurveyById
from domain.usecases.load_answers_by_survey import LoadAnswersBySurvey
from domain.usecases.save_survey_result import SaveSurveyResult, SaveSurveyResultParams
from domain.usecases.load_survey_result import LoadSurveyResult
